require("core.options")
require("core.keymaps")
require("plugins-setup")
require("core.autogroups")
require("plugins.notify")
require("plugins.filetype")
require("plugins.alpha")
require("plugins.catppuccin")
