require("core.options")
require("core.keymaps")
require("plugins-setup")
require("core.autogroups")
require("plugins.notify")
require("plugins.filetype")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.null-ls")
-- require("plugins.nvim-navic")
require("plugins.luasnippet")
require("plugins.treesitter")
require("plugins.treesitter-context")
require("plugins.toggleterm")
require("plugins.alpha")
require("plugins.catppuccin")
