vim.pack.add({
    { src = "https://github.com/desdic/macrothis.nvim" },
}, { confirm = false })

vim.defer_fn(function()
    require("macrothis").setup({ default_register = "a" })

    vim.keymap.set("n", "<leader>kkd", function()
        require("macrothis").delete()
    end, { desc = "delete" })
    vim.keymap.set("n", "<leader>kke", function()
        require("macrothis").edit()
    end, { desc = "edit" })
    vim.keymap.set("n", "<leader>kkl", function()
        require("macrothis").load()
    end, { desc = "load" })
    vim.keymap.set("n", "<leader>kkn", function()
        require("macrothis").rename()
    end, { desc = "rename" })
    vim.keymap.set("n", "<leader>kkq", function()
        require("macrothis").quickfix()
    end, { desc = "run macro on all files in quickfix" })
    vim.keymap.set("n", "<leader>kkr", function()
        require("macrothis").run()
    end, { desc = "run macro" })
    vim.keymap.set("n", "<leader>kks", function()
        require("macrothis").save()
    end, { desc = "save" })
    vim.keymap.set("n", "<leader>kkx", function()
        require("macrothis").register()
    end, { desc = "edit register" })
    vim.keymap.set("n", "<leader>kkp", function()
        require("macrothis").copy_register_printable()
    end, { desc = "Copy register as printable" })
    vim.keymap.set("n", "<leader>kkm", function()
        require("macrothis").copy_macro_printable()
    end, { desc = "Copy macro as printable" })
end, 500)
