return {
    {
        "nvim-treesitter/nvim-treesitter",
        event = { "BufReadPre", "BufNewFile" },
        lazy = false,
        build = ":TSUpdate",
        cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
        main = "nvim-treesitter.configs",
        opts = {
            ensure_installed = {
                "bash",
                "c",
                "comment",
                "cpp",
                "dockerfile",
                "glsl",
                "go",
                "gomod",
                "gosum",
                "gotmpl",
                "gowork",
                "http",
                "json",
                "json5",
                "jsonc",
                "kdl",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "meson",
                "perl",
                "php",
                "python",
                "query",
                "regex",
                "ruby",
                "rust",
                "sql",
                "toml",
                "vim",
                "vimdoc",
                "yaml",
                "zig",
            },
            indent = { enable = true, disable = {} },
            highlight = {
                enable = true, -- false will disable the whole extension
                disable = function(lang, bufnr)
                    return lang == "yaml" and vim.api.nvim_buf_line_count(bufnr) > 5000
                end,
                additional_vim_regex_highlighting = false,
            },
        },
    },
}
